version: '3.8'

services:
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-service
    hostname: pdf-service
    networks:
      - pdf-network
    ports:
      - "8081:8085"  # Map host port 8081 to container port 8085
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # Changed to dev for development
      - SERVER_PORT=8085  # Explicitly set the server port
      - APP_API_KEY=${APP_API_KEY:-default-secure-key}
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS=always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    # Uncomment and adjust for production
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G

networks:
  pdf-network:
    driver: bridge
