services:
  redis-oqe:
    image: redis:7.0-alpine
    container_name: redis-oqe
    hostname: redis-oqe
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pdf-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-service
    hostname: pdf-service
    depends_on:
      - redis-oqe
    networks:
      - pdf-network
    ports:
      - "8081:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8085
      - APP_API_KEY=${APP_API_KEY:-default-secure-key}
      - SPRING_REDIS_HOST=redis-oqe
      - SPRING_REDIS_PORT=6379
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS=always
      - MANAGEMENT_ENDPOINT_HEALTH_REDIS_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    # Uncomment and adjust for production
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G

networks:
  pdf-network:
    driver: bridge

volumes:
  redis_data:
